### ISSUE TITLE
Approve compiler ops position

### ISSUE THREAD

**Issue by eholk** [rust-lang/leadership-council#114]
@jackh726 has been working with the Foundation on a role description for a compiler operations position. The role description is ready for review and approval by the Council. This position would be funded out of the Council budget, so the main thing we need to decide is whether we are okay with that budget allocation.

I would like to invite @jackh726 to discuss this with us at the next council meeting.

I'm hoping that this will be an easy decision, but I'd allow up to 15 minutes discussion.

**Comment by Mark-Simulacrum** [comment]
I would like to direct a portion of the Council's budget to fund the T-compiler-ops proposal. We have iterated on concrete drafts of a job description for a while, but the concrete details of the role remain under some discussion (e.g., @traviscross has an alternate job description draft from the one @jackh726 has written up historically).

The proposal is to approve $30,000 of the Project budget for the compiler team leads to utilize in order to fund this role. They should determine the appropriate job description and work with the Foundation to make sure they are happy, but further involvement from the Leadership Council should not be necessary.

(It is likely that one of the existing descriptions should be utilized as a base, but this proposal explicitly puts the Council out of line-by-line review as we are the wrong audience for that, this role is primarily for T-compiler).

@rfcbot fcp merge on this proposal

**Comment by traviscross** [comment]
My view is that we should be more concrete here.  E.g., over what term is this budget to be allocated, to whom does the role report, etc.?  I believe it's more expeditious to not leave these as open questions.

The purpose of this role is to support the compiler team, and the leads get to define that at the end of the day, but still, when allocating budget, I believe we should have a bit more in front of us.

So in that light, I'd like to amend this FCP to include the details here:

https://hackmd.io/Hb8S35agRmaM4uhL9NSibg

@Mark-Simulacrum, @ehuss, @m-ou-se: Since you've already checked off, I'm interested in your confirmation or any concerns with that.

**Comment by traviscross** [comment]
cc @davidtwco @wesleywiser

**Comment by jackh726** [comment]
For posterity, here is the link to doc that I wrote: https://hackmd.io/@eholk/ByEL-2UZye

**Comment by traviscross** [comment]
Thanks @jackh726 for posting that.  I wasn't sure you wanted to share it publicly, or I would have linked it as well.

**Comment by jackh726** [comment]
The intention was to not post it publicly yet, but the cat is out of the bag on that because any sensitive information is revealed anyways in posting the counter proposal.

**Comment by traviscross** [comment]
@rfcbot reviewed

After talking with @Mark-Simulacrum, I'm satisfied that, in this case, given the context that we have, agreeing to fund a role for a "compiler ops person", and leaving it at that, with all other details to be worked out at the discretion of the compiler team leads within their purview for that team, is all we need to do.  So +1 there.

I'll note that we will need to hear back some details, such as the term over which the budget will be spent, and whether they intend to spend all of it, for our planning on other matters.  But given the modest amount, I'm happy to leave that open for now in this case.

As a general policy matter, I have some reservation that perhaps the only reason this makes sense to us here is because we've talked about it and have some rough idea in our heads already for what the role entails.  In other cases, I can imagine that we'd need more than the title of the role.  And I do worry that if we're deciding based on what's in our heads, that we might have different things in our heads, and so there may be some value in writing down and agreeing to something specific.

But, overall, I agree that the teams are the best place to decide the matters on the details, and I'd go as far as being interested to explore the question of whether we should just allocate standing budgets to the teams and take ourselves out of the role approval process entirely.

Those can be questions for another day, though.  For solving the problem at hand, @Mark-Simulacrum's proposal is good by me.

**Comment by traviscross** [comment]
The FCP has completed, and so our unanimous decision to adopt @Mark-Simulacrum's proposal can be treated as final:

> The proposal is to approve $30,000 of the Project budget for the compiler team leads to utilize in order to fund [the T-compiler-ops] role. They should determine the appropriate job description and work with the Foundation to make sure they are happy, but further involvement from the Leadership Council should not be necessary.

cc @JoelMarcey @davidtwco @wesleywiser
