### ISSUE TITLE
How to spend GSoC 2024 money

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/leadership-council#116]
### Question

Hi! GSoC 2024 is now concluded, and we have received some money from Google for each passed project ($500 per project, so $4.5k in total - this is the usual procedure in GSoC and the amount is publicly known, btw, so this is not secret in any way). The money has been wired to the Foundation, but I think that the Project should decide how to spend them.

I personally think that the most obvious way of using that money is to send them to the mentors of the GSoC projects, since they did most of the work (also, some of them are also not Project members, which means that they might not get easy access to e.g. the grants program). However, some of them have explicitly opted out of this payment, because of some legal/financial/company reasons. So I think that there's two obvious things that we could do:
1) Send $500 to each project mentor that wants to accept the money, and then put the rest towards the general Council budget (or the grants program, or something like that).
2) Send $4.5k / (number of mentors that want to accept the money) to each project mentor that wants to accept the money (i.e. spend all the GSoC money on GSoC and don't keep any leftovers).

I'd appreciate any feedback/thoughts on what to do with the money :) I think it would be the best if it was done with the council's blessing.

For the record, I was also a mentor, but I will opt out of this payment, as I was sponsored for the GSoC work through other means.

**Comment by jamesmunns** [comment]
This was discussed in the meeting today, and the Council is in favor of the second option, as it allows us to clear this amount from the budget quickly, and spend it on the people involved. We agree that the chance of this ending up with "perverse incentives" as being fairly low.

Specifically we are proposing the following:

* Send $4.5k / (number of mentors that want to accept the money) to each project mentor that wants to accept the money (i.e. spend all the GSoC money on GSoC and don't keep any leftovers).
* If someone would like to set some upper limit to accept (due to tax reasons or whatever else, e.g. "I can't accept more than $1k total"), handle those requests, distributing out the remainder evenly
* If there is any remaining amount, or no mentors accept the grant, the remaining balance will be rolled into the budget of the council to be disbursed for other project needs

The intent would be to set this as our process for this year, and if there are no issues with this, set it as policy moving forward.

@rfcbot fcp merge

**Comment by traviscross** [comment]
@rfcbot reviewed

**Comment by ehuss** [comment]
I'm going to close as this is accepted. I believe @Kobzol is coordinating the contributions (https://rust-lang.zulipchat.com/#narrow/channel/392734-council/topic/How.20to.20spend.20GSoC.202024.20money/near/484098807).
